source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'CKNameSortManager_Example' do
  pod "CKNameSortManager", :path => "../"
end

target 'CKNameSortManager_Tests' do
  pod "CKNameSortManager", :path => "../"

  
end
