source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'CKNameSortManager_Example', :exclusive => true do
  pod "CKNameSortManager", :path => "../"
end

target 'CKNameSortManager_Tests', :exclusive => true do
  pod "CKNameSortManager", :path => "../"

  
end
